# Creating Tensors
- Constant Tensors
- Variable Tensors
- Random Tensors

#### What is a tensor?
A tensor is a numerical representation of data like input or output.

In [1]:
import tensorflow as tf

#### Constant Tensors
Constant tensors can't be modified

In [2]:
# Scalar tensor
scalar = tf.constant(7)
print('Scalar tensor is:', scalar)
print('Dimension of scalar tensor:', scalar.ndim)

Scalar tensor is: tf.Tensor(7, shape=(), dtype=int32)
Dimension of scalar tensor: 0


In [3]:
# 1D tensor
vector = tf.constant([10,10])
print('Vector tensor is:', vector)
print('Dimension of vector tensor:', vector.ndim)

Vector tensor is: tf.Tensor([10 10], shape=(2,), dtype=int32)
Dimension of vector tensor: 1


In [4]:
# 2D tensor with custom datatype
matrix = tf.constant([ [10,7], [7,10] ], dtype=tf.float16)
print('Matrix tensor is:', matrix)
print('Dimension of matrix tensor:', matrix.ndim)

Matrix tensor is: tf.Tensor(
[[10.  7.]
 [ 7. 10.]], shape=(2, 2), dtype=float16)
Dimension of matrix tensor: 2


### Typecasting

In [6]:
matrix_casted = tf.cast(matrix, dtype=tf.int8)
matrix_casted

<tf.Tensor: shape=(2, 2), dtype=int8, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int8)>

#### Variable Tensors
Variable tensors are mutable

In [13]:
# 2D tensor
matrix = tf.Variable([ [10,7], [7,10] ], dtype=tf.float16)
print('Matrix tensor is:', matrix)
matrix[1,1].assign(20.5)
print('Matrix tensor after modification is:', matrix)

Matrix tensor is: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float16)>
Matrix tensor after modification is: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float16, numpy=
array([[10. ,  7. ],
       [ 7. , 20.5]], dtype=float16)>


# Random Tensors

In [45]:
# Random tensors from normal distribution
random0 = tf.random.normal(shape=(1,10))
random0

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[-0.8364757 , -1.6083385 , -2.203379  , -0.8625273 ,  2.0652692 ,
        -1.4458216 , -0.23886982, -0.34827712, -2.0801694 , -0.8323247 ]],
      dtype=float32)>

In [22]:
# Reporducable random sequence generation
random1 = tf.random.Generator.from_seed(42)
random2 = tf.random.Generator.from_seed(42)
# from_seed is used to reproduce a certain randomness
random1 = random1.normal(shape=(3,2))
random2 = random2.normal(shape=(3,2))
random1, random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

### NumPy to Tensor

In [7]:
import numpy as np

In [9]:
vec1 = np.array([1,2,3,4,5])
vec2 = tf.convert_to_tensor(vec1, dtype=tf.int8)
vec2

<tf.Tensor: shape=(5,), dtype=int8, numpy=array([1, 2, 3, 4, 5], dtype=int8)>