# Random Seeds
A random seed is a starting point to generate random numbers. Using the same seed, the random number generation can be reproduced every time the program runs.

There are two types of seeds:
- Global level seeds
- Operation level seeds

Global level seeds work in conjunction with operational level seeds to generate random numbers.

More info: https://www.tensorflow.org/api_docs/python/tf/random/set_seed



In [2]:
import tensorflow as tf

In [13]:
vector = tf.constant([ [1,2,3], [4,5,6], [7,8,9] ])
vector

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [28]:
tf.random.set_seed(1234) # Setting global level seed
shuffled = tf.random.shuffle(vector)
shuffled
# Every time you run this cell, the shuffling order will be same


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])>

What `tf.random.set_seed()` does is it defines a starting point for random sequence generation. The reason you are getting same shuffling order is that the command `tf.random.set_seed()` is also written in that cell which resets the starting point.

Let's see what happens when we defines the starting point once:


In [29]:
tf.random.set_seed(1234) # Setting global level seed

In [46]:
shuffled2 = tf.random.shuffle(vector)
shuffled2
# You should get different shuffling order every time you run this cell

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])>

When you don't define the operation level seed, as in the above example, tensorflow automatically picks an operational level seed in conjunction with your global level seed. Which means that every time the global level seed is set or reset, the same sequence will generate afterwards.

In [57]:
# Defining both global and operation level seeds
tf.random.set_seed(1234) # Setting global level seed
shuffled = tf.random.shuffle(vector, seed=100) # Defining operation level seed
shuffled
# Every time you run this cell, the shuffling order will be same



<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])>