# Generating Tensors with Pre-defined Values

In [1]:
import tensorflow as tf

In [2]:
ones = tf.ones(shape=(3,3))
ones

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [3]:
zeros = tf.zeros(shape=(4,4), dtype=tf.int8)
zeros

<tf.Tensor: shape=(4, 4), dtype=int8, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)>

In [9]:
# Ones tensor with shape as of some other tensor
tensor = tf.Variable([[1,2,3,4], [5,6,7,8]])
ones_like = tf.ones_like(tensor, dtype=tf.int8)
ones_like

<tf.Tensor: shape=(2, 4), dtype=int8, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)>

In [4]:
identity = tf.eye(4, dtype=tf.int8)
identity

<tf.Tensor: shape=(4, 4), dtype=int8, numpy=
array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)>

In [5]:
# Numpy array to tensor
import numpy as np
a = np.arange(1, 25, dtype=np.int8)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int8)

In [6]:
a_tensor = tf.constant(a)
a_tensor

<tf.Tensor: shape=(24,), dtype=int8, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int8)>

In [7]:
# Reshaping numpy array as tensor
a_tensor_reshaped = tf.constant(a, shape=(4,6))
a_tensor_reshaped

<tf.Tensor: shape=(4, 6), dtype=int8, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]], dtype=int8)>

In [8]:
# Creating a tensor with all values a specific number
a_filled = tf.fill((3,2), value=10)
a_filled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10],
       [10, 10]])>

In [11]:
# Range tensor
tensor_range = tf.range(start=0, limit=10, delta=2)
tensor_range

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>