# Operations on Tensors

In [3]:
import tensorflow as tf

In [4]:
x = tf.constant([ [10, 7], [3, 4] ])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

### Adding a New Dimension

In [5]:
# Adding a new dimension in the beginning, i-e: For shape (2, 2), adding new dim at the beginning will be (1, 2, 2)
x_mod1 = tf.expand_dims(x, axis=0)
x_mod1


<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

In [6]:
# Adding a new dimension at a custom position.

# Adding in the middle position (1)
x_mod2 = tf.expand_dims(x, axis=1)
# Adding in the end
x_mod3 = tf.expand_dims(x, axis=-1)

x_mod2, x_mod3

(<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
 array([[[10,  7]],
 
        [[ 3,  4]]])>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]])>)

### Removing Single Dimensions

In [7]:
x_mod2_squeezed = tf.squeeze(x_mod2)
x_mod2.shape, x_mod2_squeezed.shape

(TensorShape([2, 1, 2]), TensorShape([2, 2]))

### Element Wise Operations

In [8]:
# Addition
tf.add(x, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [9]:
# Subtraction
tf.subtract(x, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [10]:
# Multiplication
tf.multiply(x, 0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]])>

In [11]:
# Division
tf.divide(x, 2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

### Matrix Multiplication

In [12]:
a = tf.constant([ [1,2,3,4], [5,6,7,8] ])
b = tf.constant([ [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24] ])
a,b

(<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]])>,
 <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])>)

In [13]:
ab = tf.matmul(a,b)
ab

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[170, 180, 190, 200],
       [410, 436, 462, 488]])>

### Typecasting

In [14]:
x_float = tf.cast(x, dtype=tf.float16)
x_float

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  4.]], dtype=float16)>